apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend  
  name: recommendation-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation-con
        image: python:3.7-slim
        command: ['sh', '-c', 'echo The app is running! && sleep 3600']
        resources:
          requests:
            cpu: "200m"            
          limits:
            cpu: "300m"            
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: frontend
  name: recommendation
spec:
  selector:
    app: recommendation
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recommendation-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recommendation-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70